### ISSUE TITLE
NPM error

### ISSUE THREAD

**Issue by drixinthemix** [zademeadowshk/NEW-2025-Solana-Raydium-Sniper-Trading-Bot#13]
Hi,
I have an error when i launch the bot with "npm run start"

[14:30:40.725] INFO: Wallet Address: XXXXXXXXXXXXX
[14:30:40.726] INFO: Snipe list: false
[14:30:40.726] INFO: Check mint renounced: true
/home/tradingsol/solbot/start.ts:37
import * as path from 'path';
           ^
TypeError: Cannot read properties of undefined (reading 'isZero')
    at /home/tradingsol/solbot/start.ts:142:46
    at Generator.next (<anonymous>)
    at /home/tradingsol/solbot/start.ts:41:71
    at new Promise (<anonymous>)
    at __awaiter (/home/tradingsol/solbot/start.ts:37:12)
    at init (/home/tradingsol/solbot/start.ts:113:12)
    at /home/tradingsol/solbot/start.ts:459:9
    at Generator.next (<anonymous>)
    at /home/tradingsol/solbot/start.ts:41:71
    at new Promise (<anonymous>)

npm version : 10.0.9
node version : 23.3.0
With Linux Debian 11.

Anyone can help me :)

**Comment by zademeadowshk** [comment]
try reinstalling the bot, from scratch, or use windows if possible

**Comment by zademeadowshk** [comment]
New Updates:
Fastest Solana Mainnet API Integrated
Advanced Rug Check with Top % Holders & Potential Fake Volume Bundler Detector
Auto Snipe Ongoing Hype Launches

Remove The Previous Versions Completely & Install The New Zip File, & Run The Bot ❤️
